[package]
name = "lexigram-bin"
version = "0.7.0"
edition = "2024"

[dependencies]
lexigram = { path = "../lexigram", package = "lexigram", version = "0.7.0" }

[[bin]]
name = "lexigram"
path = "src/main.rs"
