[package]
name = "lexigram-bin"
version = "0.8.0"
edition = "2024"

[dependencies]
#lexigram-core = { path = "../lexigram-core", version = "0.8.0" }
lexigram = { path = "../lexigram", package = "lexigram", version = "0.8.0" }

[[bin]]
name = "lexigram"
path = "src/main.rs"
