[package]
name = "lexigram_lib"
version = "0.7.0"
edition = "2024"
authors = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["rtsgen"]
rtsgen = []     # text parser that generates an RTS and its symbol table, used in tests

[dependencies]
iter-index = "1.0.0"
vectree = "0.2.3"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(for_later, possible_alternative)'] }

[workspace]
members = [".", "lexigram", "build-stage1", "build-stage2", "build-rtsgen", "lexigram-bin"]
default-members = [".", "lexigram", "build-stage1", "build-stage2", "build-rtsgen"]

# Temporary:

[profile.dev]
#debug = false
