[package]
name = "lexigram_lib"
version = "0.5.4"
edition = "2024"
authors = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iter-index = "1.0.0"
vectree = "0.2.3"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(for_later, possible_alternative)'] }

[workspace]
members = [".", "lexigram", "build-stage1", "build-stage2", "build-rtsgen"]
default-members = [".", "lexigram", "build-stage1", "build-stage2", "build-rtsgen"]

# Temporary:

[profile.dev]
#debug = false

[[example]]
name = "gen_microcalc"
test = true

[[example]]
name = "microcalc"
test = true

[dev-dependencies]
lexigram = { path = "lexigram" }
