[package]
name = "lexigram_lib"
version = "0.2.0"
edition = "2024"
authors = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iter-index = "1.0.0"
vectree = "0.1.6"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(for_later, possible_alternative)'] }

[workspace]
members = [".", "lexigram", "make-gram", "make-lexi"]
default-members = [".", "lexigram", "make-gram", "make-lexi"]

# Temporary:

[profile.dev]
#debug = false
