[package]
name = "lexigram"
version = "0.2.0"
edition = "2021"
authors = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iter-index = "0.1.1"
vectree = "0.1.5"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(for_later, possible_alternative)'] }

[features]
disabled = []

[workspace]
members = [".", "gram", "lexi", "make-gram", "make-lexi"]
default-members = [".", "gram", "lexi", "make-gram", "make-lexi"]

# Temporary:

[profile.dev]
#debug = false
