[package]
name = "build-stage2"
version = "0.5.2"
edition = "2024"

[dependencies]
#lexigram_lib = { git = "ssh://git@github.com/blueglyph/lexigram.git", tag = "0.5.2", package = "lexigram_lib" }
lexigram_lib = { path = "..", package = "lexigram_lib" }
