[package]
name = "lexigram"
version = "0.4.0"
edition = "2024"

[dependencies]
#lexigram_lib = { git = "ssh://git@github.com/blueglyph/lexigram.git", tag = "0.4.0", package = "lexigram_lib" }
lexigram_lib = { path = "..", package = "lexigram_lib" }
iter-index = "0.1.1"
vectree = "0.1.4"
