[package]
name = "lexigram"
version = "0.5.3"
edition = "2024"

[dependencies]
#lexigram_lib = { git = "ssh://git@github.com/blueglyph/lexigram.git", tag = "0.5.3", package = "lexigram_lib" }
lexigram_lib = { path = "..", package = "lexigram_lib" }
iter-index = "1.0.0"
vectree = "0.2.2"
