[package]
name = "lexigram"
version = "0.8.0"
edition = "2024"

[dependencies]
#lexigram-lib = { git = "ssh://git@github.com/blueglyph/lexigram.git", tag = "0.8.0", package = "lexigram-lib" }
lexigram-lib = { path = "..", version = "0.8.0" }
iter-index = "1.0.0"
vectree = "0.2.3"
