[package]
name = "lexigram-core"
version = "0.8.0"
edition = "2024"

[features]
default = []
test_utils = []

[dependencies]

[dev-dependencies]
vectree = "0.2.3"
lexigram_lib = { path = "..", version = "0.8.0" }
