[package]
name = "lexigram-core"
version = "0.8.0"
edition = "2024"

[features]
# disable "gen_tests" if the generated code doesn't compile any more and needs updating
default = ["gen_tests"]
test_utils = []
gen_tests = []

[dependencies]
