[package]
name = "build-stage1"
version = "0.5.3"
edition = "2024"

[dependencies]
#lexigram = { git = "ssh://git@github.com/blueglyph/lexigram.git", tag = "0.5.3", package = "lexigram" }
lexigram = { path = "../lexigram", package = "lexigram" }

