[package]
name = "build-stage1"
version = "0.3.0"
edition = "2024"

[dependencies]
#lexigram = { git = "ssh://git@github.com/blueglyph/lexigram.git", tag = "0.3.0", package = "lexigram" }
lexigram = { path = "../lexigram", package = "lexigram" }
iter-index = "1.0.0"
