[package]
name = "make-lexi"
version = "0.1.0"
edition = "2024"

[dependencies]
lexigram = { path = "..", package = "lexigram" }
lexi = { path = "../lexi", package = "lexi" }
gram = { path = "../gram", package = "gram" }
iter-index = "1.0.0"
