[package]
name = "gram"
version = "0.1.0"
edition = "2024"

[dependencies]
lexigram_lib = { path = "..", package = "lexigram_lib" }
lexi = { path = "../lexi", package = "lexi" }
iter-index = "0.1.1"
vectree = "0.1.4"
